% This is a temporary build system, we would like to move to CMake. 
sourceFiles = ["cpp/proxy/mex/mex_gateway_function.cpp", ...
               "cpp/proxy/action/TypeFactory.cpp", ...
               "cpp/proxy/action/Unsupported.cpp", ...
               "cpp/proxy/action/Create.cpp", ...
               "cpp/proxy/action/Destroy.cpp", ...
               "cpp/proxy/action/MethodCall.cpp", ...
               "cpp/proxy/ProxyManager.cpp", ...
               "example/CustomProxy.cpp", ...
               "example/CustomProxyFactory.cpp"];

compilerFlags = "CXXFLAGS=$CXXFLAGS -std=c++17";
includeDirectories = ["-Icpp/", ...
                      "-I."];
verboseFlag = "-v";

mex(sourceFiles{:}, includeDirectories{:}, compilerFlags);