name: "libmexclass"
on: [push]
jobs:
    build-libmexclass:
        runs-on: ubuntu-latest
        steps:
            - name: Download libmexclass source code
              uses: actions/checkout@v3
            - name: Install MATLAB
              uses: matlab-actions/setup-matlab@v1
            - name: Build Example
              run: |
                  cd example
                  cmake -S . -B build -D CMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE"/home/runner/work/install/libmexclass
                  cmake --build build --config Release --target install
